var Rounds = [
  {
    round:1,
    regularZombies:10,
    hardenedZombies:0,
    badassZombies:0,
    superbadassZombies:0
  },{
     round:2,
     regularZombies:10,
     hardenedZombies:2,
     badassZombies:0,
     superbadassZombies:0

  },{
     round:3,
     regularZombies:15,
     hardenedZombies:6,
     badassZombies:0,
     superbadassZombies:0
  },{
     round:4,
     regularZombies:20,
     hardenedZombies:10,
     badassZombies:0,
     superbadassZombies:0
  },{
     round:5,
     regularZombies:20,
     hardenedZombies:10,
     badassZombies:0,
     superbadassZombies:0
    },{
      round:6,
      regularZombies:60,
      hardenedZombies:30,
      badassZombies:0,
      superbadassZombies:0
     },{
      round:7,
      regularZombies:80,
      hardenedZombies:40,
      badassZombies:0,
      superbadassZombies:0
     },{
      round:8,
      regularZombies:100,
      hardenedZombies:50,
      badassZombies:0,
      superbadassZombies:0
     },{
      round:9,
      regularZombies:100,
      hardenedZombies:50,
      badassZombies:0,
      superbadassZombies:0
     },{
      round:10,
      regularZombies:140,
      hardenedZombies:60,
      badassZombies:0,
      superbadassZombies:0
     },{
      round:11,
      regularZombies:200,
      hardenedZombies:100,
      badassZombies:0,
      superbadassZombies:0
     },

]

export default Rounds;